spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://centos:3306/db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
  kafka:
    bootstrap-servers: centos:9093
  data:
    elasticsearch:
      repositories:
        enabled: true
    mongodb:
      uri: mongodb://root:root@centos:27017/db?authSource=admin
  elasticsearch:
    uris: centos:9200

sa-token:
  jwt-secret-key: jwt-secret-key

properties:
  salt: salt
  whitelist: /user/**
